### ISSUE TITLE
[Etude] Choisir un format de fichier .sprt

### ISSUE THREAD

**Issue by GuillaumeGas** [GuillaumeGas/YrFight#5]

**Comment by TheNawaKer** [comment]
Voilà la structure de mon descripteur de Sprites

[struct.json.txt](https://github.com/GuillaumeGas/YrFight/files/1887905/struct.json.txt)
[example.json.txt](https://github.com/GuillaumeGas/YrFight/files/1887906/example.json.txt)

le fichier json devait porter le même nom que l'image qu'il découpait.
J'avais prévu après de créer des fichiers zip contenant le json et l'image afin de les rendre indissociable

**Comment by GuillaumeGas** [comment]
Super on se base sur ça alors !
Concernant le zip, c'est pas urgent, on verra si on peut porter la lib adéquat facilement sous Ymir ou appeler le programme qui va bien.
